### PR TITLE
Workaround for ssl issue

### PR DESCRIPTION
**Pull request by sander1**

### CODE REVIEW

**Comment by AppleTechy** [comment]
Is this currently working?

**Comment by sander1** [comment]
> Is this currently working?

This update is meant to make it work again, but it has not been pulled into this repository. You can try https://github.com/sander1/TiVoToGo.bundle

**Comment by dadrepus** [comment]
no

**Comment by dadrepus** [comment]
Well, the date works for me. Yay! I’ve tested it on my mac mini server and a mac laptop client and both played the video on one of my Tivos so great work.
Thanks so much.

**Comment by AppleTechy** [comment]
@sander1 Awesome just downloaded it, to give it ago. Will AutoDiscovery work on OS X or is it still only working on linux and can I have multiple Tivo's connected? Is there anyway for me to confirm that my TiVo is compatible with the plugin.(I have 2 Roamio Pros). I saw something about the mpeg-ts format not being supported by the plugin but that seems to be the newest format that Tivo is using and KMTTG seems to be decoding all my shows from that format. EDIT: I apparently chose the wrong ip for the Tivo, since the Roamio pros have 2 ip addresses I tried the other and it started working.

**Comment by dadrepus** [comment]
I have 3 roamio pros and this works just fine with macs. I haven’t tried with my roku's yet.

**Review by ghost — APPROVED** [review]

**Pull request closed without merging**
